services:
  betterecho:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "5000:5000"

    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      WHISPER_MODEL: small
      FLASK_ENV: development

    volumes:
      - ./frontend:/app/frontend:ro

    restart: unless-stopped
